version: '3.8'

services:
  backend:
    build:
      context: ./Server
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./Client
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
